name: Itch.io Deploy

on:
  push:
    branches:
      - main

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/export_templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s src/initial_import.gd || exit 0
          godot --editor --headless --quit || exit 0
      - name: Web Build
        run: |
          mkdir -v -p builds/web
          godot --headless -v --export-debug Web builds/web/index.html || exit 0
      - name: Sanity check
        run: |
          ls -alh builds/
          ls -alh builds/web
          stat builds/web/index.html
      - name: Deploy web build to itch.io
        run: |
          BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push builds/web ${{ vars.ITCH_GAME_ID }}:html5
